# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f425ac900ef4482eb904b88f0eb9af9cd55ba6973fa5150081bbee24b65eb9d4322ce4f92eff5941c58498504767ec9028b8d145572f197066b51bb05d05dd0b

test:
  secret_key_base: 38580f45d938ec4bac707cbd5eecf4b564edc4bd3ddfd996ba2a35f14ece5b19a3d03ce209bea6ea0083c2a1a619db3b903a65c8a48ec4453cb70df5e25c9104

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
